//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administration.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Administration.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        public static string ActionsColumn {
            get {
                return ResourceManager.GetString("ActionsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active.
        /// </summary>
        public static string ActiveCheckBox {
            get {
                return ResourceManager.GetString("ActiveCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add User.
        /// </summary>
        public static string AddUserButton {
            get {
                return ResourceManager.GetString("AddUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrival Time.
        /// </summary>
        public static string ArrivalTimeColumn {
            get {
                return ResourceManager.GetString("ArrivalTimeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available Spaces.
        /// </summary>
        public static string AvailableSpaces {
            get {
                return ResourceManager.GetString("AvailableSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blocked Requests Details:.
        /// </summary>
        public static string BlockedRequestsDetails {
            get {
                return ResourceManager.GetString("BlockedRequestsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        public static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create User.
        /// </summary>
        public static string CreateUserTitle {
            get {
                return ResourceManager.GetString("CreateUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Debug Report.
        /// </summary>
        public static string DebugReport {
            get {
                return ResourceManager.GetString("DebugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The debug report helps identify and resolve technical issues..
        /// </summary>
        public static string DebugReportDescription {
            get {
                return ResourceManager.GetString("DebugReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string EmailColumn {
            get {
                return ResourceManager.GetString("EmailColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string EmailHint {
            get {
                return ResourceManager.GetString("EmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End Date.
        /// </summary>
        public static string EndDateHint {
            get {
                return ResourceManager.GetString("EndDateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End Date and Time.
        /// </summary>
        public static string EndDateTimeHint {
            get {
                return ResourceManager.GetString("EndDateTimeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter federal tax rate.
        /// </summary>
        public static string EnterFederalTaxHint {
            get {
                return ResourceManager.GetString("EnterFederalTaxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the full-day rate.
        /// </summary>
        public static string EnterFullDayRateHint {
            get {
                return ResourceManager.GetString("EnterFullDayRateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the half-day rate.
        /// </summary>
        public static string EnterHalfDayRateHint {
            get {
                return ResourceManager.GetString("EnterHalfDayRateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the hourly rate.
        /// </summary>
        public static string EnterHourlyRateHint {
            get {
                return ResourceManager.GetString("EnterHourlyRateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter provincial tax rate.
        /// </summary>
        public static string EnterProvincialTaxHint {
            get {
                return ResourceManager.GetString("EnterProvincialTaxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Federal Tax.
        /// </summary>
        public static string FederalTaxGroup {
            get {
                return ResourceManager.GetString("FederalTaxGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First Name.
        /// </summary>
        public static string FirstNameColumn {
            get {
                return ResourceManager.GetString("FirstNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First Name.
        /// </summary>
        public static string FirstNameHint {
            get {
                return ResourceManager.GetString("FirstNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full-Day Rate.
        /// </summary>
        public static string FullDayRateGroup {
            get {
                return ResourceManager.GetString("FullDayRateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate Revenue Report.
        /// </summary>
        public static string GenerateRevenueReportButton {
            get {
                return ResourceManager.GetString("GenerateRevenueReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Half-Day Rate.
        /// </summary>
        public static string HalfDayRateGroup {
            get {
                return ResourceManager.GetString("HalfDayRateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string HomeButton {
            get {
                return ResourceManager.GetString("HomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hourly Rate.
        /// </summary>
        public static string HourlyRateGroup {
            get {
                return ResourceManager.GetString("HourlyRateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID.
        /// </summary>
        public static string IDColumn {
            get {
                return ResourceManager.GetString("IDColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EN.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Name.
        /// </summary>
        public static string LastNameColumn {
            get {
                return ResourceManager.GetString("LastNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Name.
        /// </summary>
        public static string LastNameHint {
            get {
                return ResourceManager.GetString("LastNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à License Plate.
        /// </summary>
        public static string LicensePlateColumn {
            get {
                return ResourceManager.GetString("LicensePlateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entry Type.
        /// </summary>
        public static string LogEntryTypeHint {
            get {
                return ResourceManager.GetString("LogEntryTypeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. Log Report.
        /// </summary>
        public static string LogReport {
            get {
                return ResourceManager.GetString("LogReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The log report allows you to track all system activities..
        /// </summary>
        public static string LogReportDescription {
            get {
                return ResourceManager.GetString("LogReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify.
        /// </summary>
        public static string ModifyButton {
            get {
                return ResourceManager.GetString("ModifyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parking Status.
        /// </summary>
        public static string ParkingStatus {
            get {
                return ResourceManager.GetString("ParkingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string PasswordHint {
            get {
                return ResourceManager.GetString("PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment Time.
        /// </summary>
        public static string PaymentTimeColumn {
            get {
                return ResourceManager.GetString("PaymentTimeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pie Chart Summary:.
        /// </summary>
        public static string PieChartSummary {
            get {
                return ResourceManager.GetString("PieChartSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Provincial Tax.
        /// </summary>
        public static string ProvincialTaxGroup {
            get {
                return ResourceManager.GetString("ProvincialTaxGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rates.
        /// </summary>
        public static string RatesTab {
            get {
                return ResourceManager.GetString("RatesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reason.
        /// </summary>
        public static string ReasonColumn {
            get {
                return ResourceManager.GetString("ReasonColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Report Page.
        /// </summary>
        public static string ReportHeader {
            get {
                return ResourceManager.GetString("ReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Report.
        /// </summary>
        public static string ReportPageTitle {
            get {
                return ResourceManager.GetString("ReportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Request ID.
        /// </summary>
        public static string RequestIdColumn {
            get {
                return ResourceManager.GetString("RequestIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revenue.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. Revenue Report.
        /// </summary>
        public static string RevenueReport {
            get {
                return ResourceManager.GetString("RevenueReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This report provides a comprehensive analysis of your revenue..
        /// </summary>
        public static string RevenueReportDescription {
            get {
                return ResourceManager.GetString("RevenueReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revenue Trend (Last 7 Days).
        /// </summary>
        public static string RevenueTrend {
            get {
                return ResourceManager.GetString("RevenueTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Log Report.
        /// </summary>
        public static string ShowLogReportButton {
            get {
                return ResourceManager.GetString("ShowLogReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Date.
        /// </summary>
        public static string StartDateHint {
            get {
                return ResourceManager.GetString("StartDateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Date and Time.
        /// </summary>
        public static string StartDateTimeHint {
            get {
                return ResourceManager.GetString("StartDateTimeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à State.
        /// </summary>
        public static string StateColumn {
            get {
                return ResourceManager.GetString("StateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tickets.
        /// </summary>
        public static string TicketsTab {
            get {
                return ResourceManager.GetString("TicketsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total Revenue:.
        /// </summary>
        public static string TotalRevenue {
            get {
                return ResourceManager.GetString("TotalRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unpaid Active Tickets.
        /// </summary>
        public static string UnpaidTickets {
            get {
                return ResourceManager.GetString("UnpaidTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username.
        /// </summary>
        public static string UsernameColumn {
            get {
                return ResourceManager.GetString("UsernameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username.
        /// </summary>
        public static string UsernameHint {
            get {
                return ResourceManager.GetString("UsernameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users.
        /// </summary>
        public static string UsersColumn {
            get {
                return ResourceManager.GetString("UsersColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users.
        /// </summary>
        public static string UsersTab {
            get {
                return ResourceManager.GetString("UsersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View Debug Report.
        /// </summary>
        public static string ViewDebugReportButton {
            get {
                return ResourceManager.GetString("ViewDebugReportButton", resourceCulture);
            }
        }
    }
}
